version: '2'
services:
 es:
   image: vulhub/elasticsearch:1.5.1-with-tomcat
   ports:
    - "9200:9200"
    - "9300:9300"
    - "5005:5005"
    - "8080:8080"
   environment:
    - "ES_JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
