version: '2'
services:
 spring:
   image: vulhub/spring-rest-data:2.6.6
   ports:
    - "8080:8080"
   environment:
    - "ES_JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
